### ISSUE TITLE
Increase selected line contrast / use macOS default colors?

### ISSUE THREAD

**Issue by DivineDominion** [stephanbogner/the-coding-writer-theme#1]
Am enjoying the theme!

One thing that goes against high contrast for me is the active selection:

<img width="428" alt="image" src="https://user-images.githubusercontent.com/59080/122673851-bf6f1e80-d1d2-11eb-89bf-180a3ee9d830.png">

Maybe there's a hue shift, but I have red/green deficiency and thus mostly see a slight contrast in background tone compared to the alternating background color, i.e. it's slightly darker. macOS does a great job with its inversion of text colors and the obvious accent/highlights:  

<img width="366" alt="image" src="https://user-images.githubusercontent.com/59080/122673918-170d8a00-d1d3-11eb-98fd-f7c7a04c58b0.png">

**Comment by stephanbogner** [comment]
Hey @DivineDominion – thanks for checking it out and the feedback.

Also for including a screenshot, because I've been using the theme only without alternating row colors and I overlooked that issue.

I was a bit hesitant to do the color inversion like on OSX, because I thought it would distract from the writing, but it's actually not bad:

**Focussed state:**
<img width="340" alt="Screenshot 2021-06-22 at 15 35 00" src="https://user-images.githubusercontent.com/7897006/122934745-19591b00-d370-11eb-801c-0128f5791751.png">

**Unfocussed state:**
<img width="302" alt="Screenshot 2021-06-22 at 15 39 17" src="https://user-images.githubusercontent.com/7897006/122934778-1f4efc00-d370-11eb-8de2-194442226b76.png">

(I also checked the colors with [Accessible Colors](https://accessible-colors.com/) and [Sim Daltonism](https://michelf.ca/projects/mac/sim-daltonism/) so those should work fine now)

**Comment by DivineDominion** [comment]
Looks great!
